"""Detection signals for Provenance Guard.

Signal 1: statistical analysis of the text — burstiness and lexical repetition.
Returns a score in [0, 1] where 1 = looks more AI-generated. No network needed,
so it's easy to test and inspect on its own.

Signal 2: a Groq LLM acting as a stylometric judge. Also returns a score in
[0, 1] (1 = looks AI), plus a one-line rationale. Needs the network, so it can
fail — the scorer degrades to Signal 1 alone when it does.
"""

import json
import os
import re
import statistics

# Which Groq model to use for the judge. Overridable via .env so I'm not stuck
# if a model name gets retired.
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")

# How many words a text needs before I trust the statistics. Below this I flag
# it as "short" so the scorer can refuse to be confident (see planning.md edge
# cases: very short text defeats every signal).
MIN_WORDS_FOR_CONFIDENCE = 25

# Tuning knobs (rough starting points; I'll calibrate properly in M4).
# Human prose tends to have a high coefficient of variation in sentence length
# (bursty). AI text tends to sit lower. At/above this CV I treat burstiness as
# fully human-like.
BURSTINESS_HUMAN_CV = 0.8
# Typical type-token ratio for a normal paragraph. Lower (more repetition) reads
# more AI-like in my heuristic.
LEXICAL_HUMAN_TTR = 0.65


def _split_sentences(text):
    """Very simple sentence splitter on ., !, ? — good enough for this signal."""
    parts = re.split(r"[.!?]+", text)
    return [p.strip() for p in parts if p.strip()]


def _words(text):
    return re.findall(r"\b\w+\b", text.lower())


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


def statistical_signal(text):
    """Score how AI-like a text looks based on burstiness + lexical repetition.

    Returns a dict:
        {
          "score": float in [0,1],   # 1 = looks AI, 0 = looks human
          "burstiness_cv": float,     # coefficient of variation of sentence lengths
          "type_token_ratio": float,  # unique words / total words
          "ai_from_burstiness": float,
          "ai_from_lexical": float,
          "word_count": int,
          "sentence_count": int,
          "short_text": bool,         # True = too little text to trust
        }
    """
    words = _words(text)
    sentences = _split_sentences(text)
    word_count = len(words)
    sentence_count = len(sentences)

    short_text = word_count < MIN_WORDS_FOR_CONFIDENCE or sentence_count < 2

    # --- Burstiness: coefficient of variation of sentence lengths ---
    sentence_lengths = [len(_words(s)) for s in sentences]
    if sentence_count >= 2 and statistics.mean(sentence_lengths) > 0:
        cv = statistics.pstdev(sentence_lengths) / statistics.mean(sentence_lengths)
    else:
        cv = 0.0  # can't measure variation with <2 sentences
    # Low CV (uniform sentences) -> more AI-like. Scale against the human level.
    ai_from_burstiness = _clamp(1.0 - (cv / BURSTINESS_HUMAN_CV))

    # --- Lexical repetition: type-token ratio ---
    ttr = (len(set(words)) / word_count) if word_count else 0.0
    # Lower diversity (more repetition) -> more AI-like.
    ai_from_lexical = _clamp(1.0 - (ttr / LEXICAL_HUMAN_TTR))

    # Burstiness is the stronger classic signal, so it gets more weight.
    score = 0.6 * ai_from_burstiness + 0.4 * ai_from_lexical

    return {
        "score": round(score, 4),
        "burstiness_cv": round(cv, 4),
        "type_token_ratio": round(ttr, 4),
        "ai_from_burstiness": round(ai_from_burstiness, 4),
        "ai_from_lexical": round(ai_from_lexical, 4),
        "word_count": word_count,
        "sentence_count": sentence_count,
        "short_text": short_text,
    }


# Provisional attribution from a single signal. Kept from M3 for quick local
# inspection of Signal 1 in isolation; the real fusion lives in scorer.py now.
def provisional_attribution(stat_result):
    if stat_result["short_text"]:
        return "uncertain"
    score = stat_result["score"]
    if score >= 0.65:
        return "ai"
    if score <= 0.35:
        return "human"
    return "uncertain"


# --- Signal 2: Groq LLM judge -------------------------------------------------

_JUDGE_PROMPT = (
    "You are a forensic text analyst. Decide how likely the following text was "
    "generated by an AI language model versus written by a human.\n\n"
    "Look for AI tells: even, predictable rhythm; generic transitions like "
    "'furthermore' or 'it is important to note'; over-hedging; tidy parallel "
    "structure; absence of personal voice or idiosyncrasy. Human writing tends "
    "to be burstier, more idiosyncratic, and occasionally messy.\n\n"
    "Respond with ONLY a JSON object of the form "
    '{\"p_ai\": <float 0..1>, \"rationale\": \"<one short sentence>\"} '
    "where p_ai is your probability the text is AI-generated.\n\n"
    "TEXT:\n\"\"\"\n__TEXT__\n\"\"\""
)


def llm_signal(text):
    """Ask a Groq model to judge how AI-like the text is.

    Returns a dict:
        {
          "available": bool,         # False if the API call failed
          "score": float|None,       # p_ai in [0,1], or None if unavailable
          "rationale": str,          # model's one-line reason, or an error note
        }
    The function never raises — a network/API problem just comes back as
    available=False so the scorer can fall back to Signal 1 alone.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return {"available": False, "score": None, "rationale": "GROQ_API_KEY not set."}

    try:
        from groq import Groq  # imported lazily so the stat signal has no dependency

        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[{"role": "user", "content": _JUDGE_PROMPT.replace("__TEXT__", text)}],
        )
        raw = resp.choices[0].message.content
        parsed = json.loads(raw)
        score = float(parsed.get("p_ai"))
        score = _clamp(score)  # guard against the model returning e.g. 1.2
        rationale = str(parsed.get("rationale", "")).strip() or "(no rationale given)"
        return {"available": True, "score": round(score, 4), "rationale": rationale}
    except Exception as exc:  # network error, bad JSON, retired model, etc.
        return {"available": False, "score": None, "rationale": f"LLM judge failed: {exc}"}
